리스트 추가 요청합니다.
nomadcoders/nomadcoders-github-list pull request #153
Opened 2021-03-15 16:08 UTC by hy01n

리스트 추가 요청합니다.

2021-03-22 01:16 UTC, flynnpark requested changes
노마드코더 계정 정보도 적어주시고 정렬 부탁드립니다~

2021-03-24 13:08 UTC, hy01n commented
> 노마드코더 계정 정보도 적어주시고 정렬 부탁드립니다~

변경했습니다!

2021-03-24 23:03 UTC, flynnpark approved these changes

2021-03-24 23:22 UTC, merged

2021-03-24 23:22 UTC, flynnpark commented
감사합니다~