Add 친슈
nomadcoders/nomadcoders-github-list pull request #160
Opened 2021-03-22 07:06 UTC by Achelous1

2021-03-22 13:13 UTC, flynnpark requested changes
정렬 기준을 노마드코더 닉네임으로 맞춰주시면 감사하겠습니다...!

2021-03-23 00:57 UTC, Achelous1 commented
> 정렬 기준을 노마드코더 닉네임으로 맞춰주시면 감사하겠습니다...!

노마드코더 유저명 변경하여 반영했습니다 :D

2021-03-25 00:17 UTC, flynnpark commented
노마드코더 유저 정보 조회가 안 되네요... 계정 확인 부탁드립니다.

2021-03-25 00:27 UTC, flynnpark approved these changes
좋습니당

2021-03-25 00:30 UTC, merged